# This file was generated by GoReleaser. DO NOT EDIT.
cask "civitai" do
  version "0.1.69"

  on_macos do
    on_intel do
      sha256 "ef10cd10a26c85e383ed3ea91ec93aa8d5bad86f158e22a25a69da8e084c69fa"
      url "https://github.com/civitai/cli/releases/download/v#{version}/civitai_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "970999737e9a00242e6031290b54db2590f51e056a5debb8ff2f93797abf69b6"
      url "https://github.com/civitai/cli/releases/download/v#{version}/civitai_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0765b86b5da4edfd8556c3df0d6261c1d9c79656248cdb0e3358c92ab8e06505"
      url "https://github.com/civitai/cli/releases/download/v#{version}/civitai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ecacbd30b754f5bd999af8bb935fb4fc0e4c425f689a7ea339b972c05fb0a361"
      url "https://github.com/civitai/cli/releases/download/v#{version}/civitai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "civitai"
  desc "Civitai CLI — author and ship Apps"
  homepage "https://github.com/civitai/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "civitai"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/civitai"]
    end
  end

  # No zap stanza required

end
