# This file was generated by GoReleaser. DO NOT EDIT.
cask "civitai" do
  version "0.1.106"

  on_macos do
    on_arm do
      sha256 "0c30fe9bda430340602b8b098a969bdd0ac5081fa3155b66cc98fb81bcadafa5"
      url "https://github.com/civitai/cli/releases/download/v#{version}/civitai_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "38e7054a9053da3c9eb71edd614fc3871a3fccaffe7e9c40d29103910510cd82"
      url "https://github.com/civitai/cli/releases/download/v#{version}/civitai_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "986057aa79c0578f3827b3591461c8ecd3f2f0af262908ef25e3d338d2410fdb"
      url "https://github.com/civitai/cli/releases/download/v#{version}/civitai_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e402c3718ab980c9b498fdb4c3a84561ab7a76bf317615bab753236a25b3ef95"
      url "https://github.com/civitai/cli/releases/download/v#{version}/civitai_#{version}_linux_amd64.tar.gz"
    end
  end

  name "civitai"
  desc "Civitai CLI — author and ship Apps"
  homepage "https://github.com/civitai/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "civitai"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/civitai"]
    end
  end

  # No zap stanza required
end
