# This file was generated by GoReleaser. DO NOT EDIT.
cask "civitai" do
  version "0.1.55"

  on_macos do
    on_intel do
      sha256 "94ba6c8733670a6987f81507d020602b1a2e5182a412982a57230955e654579f"
      url "https://github.com/civitai/cli/releases/download/v#{version}/civitai_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f938fee33337111aa2a46aa8bf9dbb73e5b599cc6bc558030d3e8e628a87c637"
      url "https://github.com/civitai/cli/releases/download/v#{version}/civitai_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d875b9b02a4c3853ccd0e2ffb4930c5a3b9aab58f73dc979d60696036ab45271"
      url "https://github.com/civitai/cli/releases/download/v#{version}/civitai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4da999c3083e7a8bee4fb3819dbbaa17bba1437015a32ef223dbb49d7ae45fdb"
      url "https://github.com/civitai/cli/releases/download/v#{version}/civitai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "civitai"
  desc "Civitai CLI — author and ship Apps"
  homepage "https://github.com/civitai/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "civitai"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/civitai"]
    end
  end

  # No zap stanza required

end
